version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: localhost
    ports:
      - 5672:5672
      - 15672:15672

  pg_f:
    image: postgres:latest
    container_name: pg_f
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=first_db
    ports:
      - 5431:5432

  pg_s:
    image: postgres:latest
    container_name: pg_s
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=second_db
    ports:
      - 5432:5432

  flyway_f:
    image: flyway/flyway
    command: -url=jdbc:postgresql://pg_f:5431/first_db -schemas=public -user=root -password=password -connectRetries=60 clean migrate
    volumes:
      - ../micro-service-task/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - pg_f
      - pg_s

  flyway_s:
    image: flyway/flyway
    command: -url=jdbc:postgresql://pg_s:5432/second_db -schemas=public -user=root -password=root -connectRetries=60 clean migrate
    volumes:
      - ../micro-service-task-second/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - pg_s
      - pg_f

  first:
    image: first
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_f:5431/first_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - pg_f
      - rabbitmq
    ports:
      - 8080:8080

  second:
    image: second
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_s:5432/second_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - pg_s
      - rabbitmq
      - first
    ports:
      - 8081:8081
    networks:
      - pg_s_net

networks:
  pg_s_net:
  pg_f_net:
    driver: bridge