version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq

  pg_f:
    image: postgres:latest
    container_name: pg_f
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=first_db

  pg_s:
    image: postgres:latest
    container_name: pg_s
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=second_db

  flyway_f:
    image: flyway/flyway
    command: -url=jdbc:postgresql://pg_f:5432/first_db -schemas=public -user=root -password=root -connectRetries=60 clean migrate
    volumes:
      - ../micro-service-task/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - pg_f

  flyway_s:
    image: flyway/flyway
    command: -url=jdbc:postgresql://pg_s:5432/second_db -schemas=public -user=root -password=root -connectRetries=60 clean migrate
    volumes:
      - ../micro-service-task-second/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - pg_s

  first:
    image: first
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_f:5432/first_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - pg_f
      - rabbitmq
    ports:
      - 8080:8080

  second:
    image: second
    build:
      context: ../micro-service-task-second
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_s:5432/second_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - pg_s
      - rabbitmq
    ports:
      - 8081:8081